#ifndef SERVER_PORT_DEFH
#define SERVER_PORT_DEFH

#define	ACCSVR_ACCOUNT_VERIFY_PORT		5002
#define ROLEDBSVR_ROLEDB_PORT			5001
#define	GATEWAY_USER_VERIFY_PORT		5622
#define	GATEWAY_GAMESVR_SERVICE_PORT	5632
#define	GAEMSVR_USER_SERVICE_PORT		6666
#define	RELAY_GAMESVR_SERVICE_PORT		5003	//使用的是扩展协议
#define	RELAY_GAMESVR_CHATSERVICE_PORT	5004	//使用的是标准协议
#define RELAY_GAMESVR_TONGSERVICE_PORT	5005	//使用的是扩展协议
#define	RELAY_SIBLING_PORT				7776	//使用的是扩展协议
#define	RELAY_ROUTE_PORT				7777	//使用的是扩展协议
#endif
