#ifndef _FONTDEF_H_
#define _FONTDEF_H_

enum CHARACTER_CODE_SET
{
	CHARACTER_CODE_SET_GBK	= 1,	//GBK±àÂë
	CHARACTER_CODE_SET_GB2132,		//GB2132±àÂë
};

#define	KRF_ZERO_END	-1
#define	KRF_FOLLOW		(-2147483647 - 1)


#endif