#ifndef KMagicAttribH
#define KMagicAttribH

#define	INVALID_ATTRIB	-1
// 枚举类型最后一个字母表示该数值的类型，v为整型，直接加的点数，p为百分比，b为布尔型
enum MAGIC_ATTRIB
{
//改变技能的属性
	magic_skill_begin,
	magic_skill_cost_v,								// 消耗MANA
	magic_skill_costtype_v,							//	
	magic_skill_mintimepercast_v,					// 每次发魔法的间隔时间
	magic_skill_misslenum_v,						// 
	magic_skill_misslesform_v,		
	magic_skill_param1_v,		
	magic_skill_param2_v,
	magic_skill_reserve1,
	magic_skill_reserve2,
	magic_skill_reserve3,
	magic_skill_reserve4,
	magic_skill_eventskilllevel,
	magic_skill_end,
//改变发出子弹的属性
	magic_missle_begin,
	magic_missle_movekind_v,						// 子弹格式
	magic_missle_speed_v,							// 子弹飞行速度
	magic_missle_lifetime_v,						// 子弹的生命时间
	magic_missle_height_v,							// 子弹的高度
	magic_missle_damagerange_v,						// 子弹破坏范围
	magic_missle_radius_v,							// 子弹飞行半径
	magic_missle_reserve1,
	magic_missle_reserve2,
	magic_missle_reserve3,
	magic_missle_reserve4,
	magic_missle_reserve5,
	magic_missle_end,
//装备属性	
	magic_item_begin,
	magic_weapondamagemin_v,
	magic_weapondamagemax_v,
	magic_armordefense_v,
	magic_durability_v,
	magic_requirestr,
	magic_requiredex,
	magic_requirevit,
	magic_requireeng,
	magic_requirelevel,
	magic_requireseries,
	magic_requiresex,
	magic_requiremenpai,
	magic_weapondamageenhance_p,
	magic_armordefenseenhance_p,
	magic_requirementreduce_p,
	magic_indestructible_b,
	magic_item_reserve1,
	magic_item_reserve2,
	magic_item_reserve3,
	magic_item_reserve4,
	magic_item_reserve5,
	magic_item_reserve6,
	magic_item_reserve7,
	magic_item_reserve8,
	magic_item_reserve9,
	magic_item_reserve10,
	magic_item_end,
//主动攻击伤害属性
	magic_damage_begin,		
	magic_attackrating_v,
	magic_attackrating_p,
	magic_ignoredefense_p,
	magic_physicsdamage_v,
	magic_colddamage_v,
	magic_firedamage_v,
	magic_lightingdamage_v,
	magic_poisondamage_v,
	magic_magicdamage_v,
	magic_physicsenhance_p,
	magic_steallife_p,
	magic_stealmana_p,
	magic_stealstamina_p,
	magic_knockback_p,
	magic_deadlystrike_p,
	magic_fatallystrike_p,
	magic_stun_p,
	magic_damage_reserve1,
	magic_damage_reserve2,
	magic_damage_reserve3,
	magic_damage_reserve4,
	magic_damage_reserve5,
	magic_damage_reserve6,
	magic_damage_reserve7,
	magic_damage_reserve8,
	magic_damage_reserve9,
	magic_damage_reserve10,
	magic_damage_end,
//被动、状态、光环类属性
	magic_normal_begin,
	magic_lifemax_v,
	magic_lifemax_p,
	magic_life_v,
	magic_lifereplenish_v,
	magic_manamax_v,
	magic_manamax_p,
	magic_mana_v,
	magic_manareplenish_v,
	magic_staminamax_v,
	magic_staminamax_p,
	magic_stamina_v,
	magic_staminareplenish_v,
	magic_strength_v,
	magic_dexterity_v,
	magic_vitality_v,
	magic_energy_v,
	magic_poisonres_p,
	magic_fireres_p,
	magic_lightingres_p,
	magic_physicsres_p,
	magic_coldres_p,
	magic_freezetimereduce_p,
	magic_burntimereduce_p,
	magic_poisontimereduce_p,
	magic_poisondamagereduce_v,
	magic_stuntimereduce_p,
	magic_fastwalkrun_p,
	magic_visionradius_p,
	magic_fasthitrecover_v,
	magic_allres_p,
	magic_attackspeed_v,
	magic_castspeed_v,
	magic_meleedamagereturn_v,
	magic_meleedamagereturn_p,
	magic_rangedamagereturn_v,
	magic_rangedamagereturn_p,
	magic_addphysicsdamage_v,
	magic_addfiredamage_v,
	magic_addcolddamage_v,
	magic_addlightingdamage_v,
	magic_addpoisondamage_v,
	magic_addphysicsdamage_p,
	magic_slowmissle_b,
	magic_changecamp_b,
	magic_physicsarmor_v,
	magic_coldarmor_v,
	magic_firearmor_v,
	magic_poisonarmor_v,
	magic_lightingarmor_v,
	magic_damagetomana_p,
	magic_lucky_v,
	magic_steallifeenhance_p,
	magic_stealmanaenhance_p,
	magic_stealstaminaenhance_p,
	magic_allskill_v,
	magic_metalskill_v,
	magic_woodskill_v,
	magic_waterskill_v,
	magic_fireskill_v,
	magic_earthskill_v,
	magic_knockbackenhance_p,
	magic_deadlystrikeenhance_p,
	magic_stunenhance_p,
	magic_badstatustimereduce_v,
	magic_manashield_p,
	magic_adddefense_v,
	magic_adddefense_p,
	magic_fatallystrikeenhance_p,
	magic_lifepotion_v,
	magic_manapotion_v,
	magic_physicsresmax_p,
	magic_coldresmax_p,
	magic_fireresmax_p,
	magic_lightingresmax_p,
	magic_poisonresmax_p,
	magic_allresmax_p,
	magic_coldenhance_p,
	magic_fireenhance_p,
	magic_lightingenhance_p,
	magic_poisonenhance_p,
	magic_magicenhance_p,
	magic_attackratingenhance_v,
	magic_attackratingenhance_p,
	magic_normal_end,
};

extern const char MAGIC_ATTRIB_STRING[magic_normal_end + 1][100] ; 


#endif
